// Port of DisplayLanguage + LocalizationService: English and Simplified
// Chinese, 'system' follows the browser locale. Unknown keys return the key.
export const LANGUAGE_SYSTEM = "system";
export const LANGUAGE_ENGLISH = "en-US";
export const LANGUAGE_CHINESE = "zh-Hans";

export function normalizeLanguage(language: string | null | undefined): string {
  const trimmed = language?.trim();
  if (!trimmed) return LANGUAGE_SYSTEM;
  if (trimmed.toLowerCase() === LANGUAGE_SYSTEM) return LANGUAGE_SYSTEM;
  if (/^zh/i.test(trimmed)) return LANGUAGE_CHINESE;
  if (/^en/i.test(trimmed)) return LANGUAGE_ENGLISH;
  return LANGUAGE_SYSTEM;
}

export function resolveLanguage(preferred: string): "en-US" | "zh-Hans" {
  const normalized = normalizeLanguage(preferred);
  if (normalized === LANGUAGE_CHINESE) return "zh-Hans";
  if (normalized === LANGUAGE_ENGLISH) return "en-US";
  return /^zh/i.test(navigator.language) ? "zh-Hans" : "en-US";
}

const en: Record<string, string> = {
  AppTitle: "Lumina",
  Locations: "Locations",
  Tags: "Tags",
  Settings: "Settings",
  ShowSidebar: "Show sidebar",
  HideSidebar: "Hide sidebar",
  AddLocation: "Add location",
  ClearLocations: "Clear all",
  ClearLocationsConfirm: "Remove all managed folders? Files on disk are not touched.",
  DemoLocation: "Demo library",
  AddDemoLocation: "Add demo library",
  LocationsEmpty: "Managed folders will appear here.",
  RenameLocation: "Rename",
  RemoveLocation: "Remove",
  NoLocationSelected: "No location selected",
  NoLocationHint: "Choose a managed folder from the Locations pane.",
  FsaUnsupported: "This browser cannot open local folders. Use Chrome or Edge, or try the demo library.",
  Search: "Search",
  SearchInFolder: "Search in {0}",
  Loading: "Loading folder...",
  EmptyFolder: "This folder is empty",
  EmptyFolderHint: "Files and folders will appear here.",
  Back: "Back",
  Forward: "Forward",
  UpOneLevel: "Up one level",
  Refresh: "Refresh",
  NewFolder: "New folder",
  SortBy: "Sort",
  SortName: "Name",
  SortModified: "Date modified",
  SortType: "Type",
  SortSize: "Size",
  SortAscending: "Ascending",
  SortDescending: "Descending",
  Folder: "Folder",
  Rename: "Rename",
  Delete: "Delete",
  DeleteConfirm: "Permanently delete {0} item(s)? This cannot be undone.",
  Open: "Open",
  OpenContainingFolder: "Open containing folder: {0}",
  ShowInExplorer: "Show in File Explorer",
  DeleteConfirmTrash: "Move {0} item(s) to the Recycle Bin?",
  FileOperationCopyTitle: "Copying items",
  FileOperationMoveTitle: "Moving items",
  FileOperationDeleteTitle: "Deleting items",
  FileOperationPreparing: "Preparing {0} item(s)...",
  FileOperationBytesProgress: "{0} of {1}",
  FileOperationItemsProgress: "{0} of {1} items",
  FileOperationCancelling: "Cancelling...",
  FileConflictTitle: "File conflict",
  FileConflictMessage: "The destination already contains an item named {0}.",
  PasteInterruptedTitle: "Paste interrupted",
  PasteSameFolderMessage: "The source and destination folders are the same: {0}",
  ConflictSource: "Source",
  ConflictDestination: "Destination",
  ConflictSkip: "Skip",
  ConflictKeepBoth: "Keep both",
  ConflictReplace: "Replace",
  UnknownDate: "Unknown date",
  FailedLoadFolder: "Could not load this folder: {0}",
  FailedOpenLocation: "Could not open this location: {0}",
  TagFilterEmpty: "No tags in your library yet.",
  ClearTagFilters: "Clear filters",
  TagGroups: "Tag groups",
  AddTagGroup: "Add group",
  AddTag: "Add tag",
  EditTag: "Edit tag",
  EditGroup: "Edit group",
  DeleteGroup: "Delete group",
  DeleteTag: "Delete tag",
  RemoveTagFromFile: "Remove tag",
  TagsEmpty: "No tag groups yet",
  TagsEmptyHint: "Create a group, then add tags you can drop onto files.",
  UntitledGroup: "Untitled group",
  UntitledTag: "Untitled tag",
  Name: "Name",
  Description: "Description",
  Color: "Color",
  TextColor: "Text color",
  Save: "Save",
  Cancel: "Cancel",
  Close: "Close",
  ExportTags: "Export",
  ImportTags: "Import",
  ImportResult: "Imported {0} group(s), {1} tag(s) from {2}.",
  ImportFailed: "Import failed: {0}",
  ClearTags: "Clear all",
  ClearTagsConfirm: "Delete the entire tag library? Filenames are not changed.",
  Language: "Language",
  LanguageSystem: "Use system setting",
  LanguageEnglish: "English",
  LanguageChinese: "简体中文",
  Background: "Background",
  BackgroundImage: "Background image",
  BackgroundDefault: "Default gradient",
  ChooseBackgroundImage: "Choose image",
  RestoreDefaultBackground: "Restore default",
  DesktopWallpaperOnly: "Custom background images are available in the desktop app.",
  WallpaperChooseFailed: "Could not use that background image: {0}",
  HideFileExtension: "Hide file extensions",
  ShowParentFolder: "Show parent folder in search results",
  SettingsAppearance: "Appearance",
  SettingsBehavior: "Behavior",
  SettingsGlass: "Liquid glass",
  SettingsAbout: "About",
  AboutApplication: "Application",
  CurrentVersion: "Current version",
  Distribution: "Distribution",
  DistributionInstalled: "Installed",
  DistributionPortable: "Portable",
  DistributionDevelopment: "Development",
  Updates: "Updates",
  CheckForUpdates: "Check for updates",
  DownloadUpdate: "Download update",
  RestartAndInstall: "Restart and install",
  OpenReleasePage: "Open release page",
  UpdateReadyStatus: "Ready to check for updates.",
  UpdateCheckingStatus: "Checking for updates...",
  UpdateAvailableStatus: "Version {0} is available.",
  UpdateUpToDateStatus: "Lumina is up to date.",
  UpdateDownloadingStatus: "Downloading version {0}... {1}%",
  UpdateDownloadedStatus: "Version {0} is ready to install.",
  UpdateInstallingStatus: "Restarting to install the update...",
  UpdateErrorStatus: "The update could not be completed.",
  UpdateDevelopmentStatus: "Update checks are disabled in development builds.",
  UpdatePortableNote: "Portable builds can check for updates, but must be replaced manually.",
  UpdateDesktopOnly: "Update checks are available in the packaged desktop app.",
  UpdateActionFailed: "Update action failed: {0}",
  UpdateAvailableTitle: "Lumina {0} is available",
  UpdateReadyToInstallTitle: "Lumina {0} is ready to install",
  GlassMode: "Refraction mode",
  GlassModeStandard: "Standard",
  GlassModePolar: "Polar",
  GlassModeProminent: "Prominent",
  GlassModeShader: "Shader (experimental)",
  GlassDisplacement: "Displacement scale",
  GlassDisplacementHint: "Intensity of edge distortion",
  GlassBlur: "Blur amount",
  GlassBlurHint: "Backdrop blur intensity",
  GlassSaturation: "Saturation",
  GlassSaturationHint: "Color saturation of the backdrop",
  GlassAberration: "Chromatic aberration",
  GlassAberrationHint: "RGB channel separation intensity",
  GlassElasticity: "Elasticity",
  GlassElasticityHint: "How much the glass reaches toward the cursor",
  GlassCornerRadius: "Corner radius",
  GlassCornerRadiusHint: "Roundness of the glass corners",
  GlassOverLight: "Over light",
  GlassOverLightHint: "Tint the glass dark for bright backgrounds",
  GlassPreview: "Preview",
  ResetDefaults: "Reset to defaults",
  DropTagHint: "Drop to tag",
  ItemsCount: "{0} items",
  SelectedCount: "{0} selected",
};

const zh: Record<string, string> = {
  AppTitle: "Lumina",
  Locations: "位置",
  Tags: "标签",
  Settings: "设置",
  ShowSidebar: "显示侧边栏",
  HideSidebar: "隐藏侧边栏",
  AddLocation: "添加位置",
  ClearLocations: "全部清除",
  ClearLocationsConfirm: "移除所有管理的文件夹？磁盘上的文件不会受影响。",
  DemoLocation: "演示库",
  AddDemoLocation: "添加演示库",
  LocationsEmpty: "管理的文件夹将显示在这里。",
  RenameLocation: "重命名",
  RemoveLocation: "移除",
  NoLocationSelected: "未选择位置",
  NoLocationHint: "请从“位置”面板选择一个管理的文件夹。",
  FsaUnsupported: "此浏览器无法打开本地文件夹。请使用 Chrome 或 Edge，或试试演示库。",
  Search: "搜索",
  SearchInFolder: "在 {0} 中搜索",
  Loading: "正在加载文件夹...",
  EmptyFolder: "此文件夹为空",
  EmptyFolderHint: "文件和文件夹将显示在这里。",
  Back: "后退",
  Forward: "前进",
  UpOneLevel: "上一级",
  Refresh: "刷新",
  NewFolder: "新建文件夹",
  SortBy: "排序",
  SortName: "名称",
  SortModified: "修改日期",
  SortType: "类型",
  SortSize: "大小",
  SortAscending: "升序",
  SortDescending: "降序",
  Folder: "文件夹",
  Rename: "重命名",
  Delete: "删除",
  DeleteConfirm: "永久删除 {0} 个项目？此操作无法撤消。",
  Open: "打开",
  OpenContainingFolder: "打开所在文件夹：{0}",
  ShowInExplorer: "在文件资源管理器中显示",
  DeleteConfirmTrash: "将 {0} 个项目移到回收站？",
  FileOperationCopyTitle: "正在复制项目",
  FileOperationMoveTitle: "正在移动项目",
  FileOperationDeleteTitle: "正在删除项目",
  FileOperationPreparing: "正在准备 {0} 个项目……",
  FileOperationBytesProgress: "{0} / {1}",
  FileOperationItemsProgress: "已处理 {0} / {1} 个项目",
  FileOperationCancelling: "正在取消……",
  FileConflictTitle: "文件冲突",
  FileConflictMessage: "目标文件夹已包含同名项目：{0}",
  PasteInterruptedTitle: "粘贴已中断",
  PasteSameFolderMessage: "源文件夹和目标文件夹相同：{0}",
  ConflictSource: "源",
  ConflictDestination: "目标",
  ConflictSkip: "跳过",
  ConflictKeepBoth: "保留两个",
  ConflictReplace: "替换",
  UnknownDate: "未知日期",
  FailedLoadFolder: "无法加载此文件夹：{0}",
  FailedOpenLocation: "无法打开此位置：{0}",
  TagFilterEmpty: "标签库中还没有标签。",
  ClearTagFilters: "清除筛选",
  TagGroups: "标签组",
  AddTagGroup: "添加组",
  AddTag: "添加标签",
  EditTag: "编辑标签",
  EditGroup: "编辑组",
  DeleteGroup: "删除组",
  DeleteTag: "删除标签",
  RemoveTagFromFile: "移除标签",
  TagsEmpty: "还没有标签组",
  TagsEmptyHint: "创建一个组，然后添加可拖放到文件上的标签。",
  UntitledGroup: "未命名组",
  UntitledTag: "未命名标签",
  Name: "名称",
  Description: "描述",
  Color: "颜色",
  TextColor: "文字颜色",
  Save: "保存",
  Cancel: "取消",
  Close: "关闭",
  ExportTags: "导出",
  ImportTags: "导入",
  ImportResult: "已从 {2} 导入 {0} 个组、{1} 个标签。",
  ImportFailed: "导入失败：{0}",
  ClearTags: "全部清除",
  ClearTagsConfirm: "删除整个标签库？文件名不会更改。",
  Language: "语言",
  LanguageSystem: "使用系统设置",
  LanguageEnglish: "English",
  LanguageChinese: "简体中文",
  Background: "背景",
  BackgroundImage: "背景图",
  BackgroundDefault: "默认渐变",
  ChooseBackgroundImage: "选择图片",
  RestoreDefaultBackground: "恢复默认",
  DesktopWallpaperOnly: "自定义背景图仅在桌面版可用。",
  WallpaperChooseFailed: "无法使用这张背景图：{0}",
  HideFileExtension: "隐藏文件扩展名",
  ShowParentFolder: "在搜索结果中显示上级文件夹",
  SettingsAppearance: "外观",
  SettingsBehavior: "行为",
  SettingsGlass: "液态玻璃",
  SettingsAbout: "关于",
  AboutApplication: "应用信息",
  CurrentVersion: "当前版本",
  Distribution: "分发类型",
  DistributionInstalled: "安装版",
  DistributionPortable: "便携版",
  DistributionDevelopment: "开发环境",
  Updates: "更新",
  CheckForUpdates: "检查更新",
  DownloadUpdate: "下载更新",
  RestartAndInstall: "重启并安装",
  OpenReleasePage: "打开发布页面",
  UpdateReadyStatus: "可以检查是否有新版本。",
  UpdateCheckingStatus: "正在检查更新……",
  UpdateAvailableStatus: "发现新版本 {0}。",
  UpdateUpToDateStatus: "Lumina 已是最新版本。",
  UpdateDownloadingStatus: "正在下载版本 {0}……{1}%",
  UpdateDownloadedStatus: "版本 {0} 已下载，可以安装。",
  UpdateInstallingStatus: "正在重启并安装更新……",
  UpdateErrorStatus: "无法完成更新。",
  UpdateDevelopmentStatus: "开发版本不执行更新检查。",
  UpdatePortableNote: "便携版可以检查更新，但需要手动下载并替换。",
  UpdateDesktopOnly: "更新检查仅在打包后的桌面应用中可用。",
  UpdateActionFailed: "更新操作失败：{0}",
  UpdateAvailableTitle: "Lumina {0} 可更新",
  UpdateReadyToInstallTitle: "Lumina {0} 可以安装",
  GlassMode: "折射模式",
  GlassModeStandard: "标准",
  GlassModePolar: "极坐标",
  GlassModeProminent: "突出",
  GlassModeShader: "着色器（实验性）",
  GlassDisplacement: "位移强度",
  GlassDisplacementHint: "控制边缘扭曲的强度",
  GlassBlur: "模糊强度",
  GlassBlurHint: "控制背景模糊的强度",
  GlassSaturation: "饱和度",
  GlassSaturationHint: "控制背景色彩的饱和度",
  GlassAberration: "色差",
  GlassAberrationHint: "控制 RGB 通道分离的强度",
  GlassElasticity: "弹性",
  GlassElasticityHint: "控制玻璃向光标伸展的程度",
  GlassCornerRadius: "圆角",
  GlassCornerRadiusHint: "控制玻璃圆角的大小",
  GlassOverLight: "亮背景模式",
  GlassOverLightHint: "将玻璃调暗，适合明亮的背景",
  GlassPreview: "预览",
  ResetDefaults: "恢复默认",
  DropTagHint: "放下以添加标签",
  ItemsCount: "{0} 个项目",
  SelectedCount: "已选择 {0} 个",
};

const dictionaries: Record<"en-US" | "zh-Hans", Record<string, string>> = {
  "en-US": en,
  "zh-Hans": zh,
};

export function translate(
  language: "en-US" | "zh-Hans",
  key: string,
  ...args: (string | number)[]
): string {
  const template = dictionaries[language][key] ?? key;
  return template.replace(/\{(\d+)\}/g, (match, index) => {
    const value = args[Number(index)];
    return value === undefined ? match : String(value);
  });
}
